name: 'Jest Action'
description: 'Runs jest with shards and outputs coverage'
author: 'imadx (ahtimadhusanka@gmail.com)'
inputs:
  milliseconds:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: 'npm run dist/index.js'
      shell: bash
