name: 'Jest Action'
description: 'Runs jest with shards and outputs coverage'
author: 'imadx (ahtimadhusanka@gmail.com)'
inputs:
  milliseconds:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
